from django.conf.urls import patterns, url



from teacher.views.teacher_personal_detail_views import *
urlpatterns = patterns('',
    url(
        regex=r'^teacher_personal_detail/archive/$',
        view=Teacher_personal_detailArchiveIndexView.as_view(),
        name='teacher_teacher_personal_detail_archive_index'
    ),
    url(
        regex=r'^teacher_personal_detail/create/$',
        view=Teacher_personal_detailCreateView.as_view(),
        name='teacher_teacher_personal_detail_create'
    ),
    url(
        regex=r'^teacher_personal_detail/(?P<year>\d{4})/'
               '(?P<month>\d{1,2})/'
               '(?P<day>\d{1,2})/'
               '(?P<pk>\d+?)/$',
        view=Teacher_personal_detailDateDetailView.as_view(),
        name='teacher_teacher_personal_detail_date_detail'
    ),
    url(
        regex=r'^teacher_personal_detail/archive/(?P<year>\d{4})/'
               '(?P<month>\d{1,2})/'
               '(?P<day>\d{1,2})/$',
        view=Teacher_personal_detailDayArchiveView.as_view(),
        name='teacher_teacher_personal_detail_day_archive'
    ),
    url(
        regex=r'^teacher_personal_detail/(?P<pk>\d+?)/delete/$',
        view=Teacher_personal_detailDeleteView.as_view(),
        name='teacher_teacher_personal_detail_delete'
    ),
    url(
        regex=r'^teacher_personal_detail/(?P<pk>\d+?)/$',
        view=Teacher_personal_detailDetailView.as_view(),
        name='teacher_teacher_personal_detail_detail'
    ),
    url(
        regex=r'^teacher_personal_detail/$',
        view=Teacher_personal_detailListView.as_view(),
        name='teacher_teacher_personal_detail_list'
    ),
    url(
        regex=r'^teacher_personal_detail/archive/(?P<year>\d{4})/'
               '(?P<month>\d{1,2})/$',
        view=Teacher_personal_detailMonthArchiveView.as_view(),
        name='teacher_teacher_personal_detail_month_archive'
    ),
    url(
        regex=r'^teacher_personal_detail/today/$',
        view=Teacher_personal_detailTodayArchiveView.as_view(),
        name='teacher_teacher_personal_detail_today_archive'
    ),
    url(
        regex=r'^teacher_personal_detail/(?P<pk>\d+?)/update/$',
        view=Teacher_personal_detailUpdateView.as_view(),
        name='teacher_teacher_personal_detail_update'
    ),
    url(
        regex=r'^teacher_personal_detail/archive/(?P<year>\d{4})/'
               '(?P<month>\d{1,2})/'
               'week/(?P<week>\d{1,2})/$',
        view=Teacher_personal_detailWeekArchiveView.as_view(),
        name='teacher_teacher_personal_detail_week_archive'
    ),
    url(
        regex=r'^teacher_personal_detail/archive/(?P<year>\d{4})/$',
        view=Teacher_personal_detailYearArchiveView.as_view(),
        name='teacher_teacher_personal_detail_year_archive'
    ),
    url(
        regex=r'^teacher_personal_detail/pool_detail$',
        view=Teacher_personal_detailPoolView.as_view(),
        name='teacher_teacher_personal_detail_pool_detail'
    ),
    url(
        regex=r'^teacher_personal_detail/pool_update/(?P<pk>\d+?)/$',
        view=Teacher_personal_detailPoolUpdateView.as_view(),
        name='teacher_teacher_personal_detail_pool_update'
    ),
)


from teacher.views.teacher_family_detail_views import *
urlpatterns += patterns('',
    url(
        regex=r'^teacher_family_detail/archive/$',
        view=Teacher_family_detailArchiveIndexView.as_view(),
        name='teacher_teacher_family_detail_archive_index'
    ),
    url(
        regex=r'^teacher_family_detail/create/$',
        view=Teacher_family_detailCreateView.as_view(),
        name='teacher_teacher_family_detail_create'
    ),
    url(
        regex=r'^teacher_family_detail/(?P<year>\d{4})/'
               '(?P<month>\d{1,2})/'
               '(?P<day>\d{1,2})/'
               '(?P<pk>\d+?)/$',
        view=Teacher_family_detailDateDetailView.as_view(),
        name='teacher_teacher_family_detail_date_detail'
    ),
    url(
        regex=r'^teacher_family_detail/archive/(?P<year>\d{4})/'
               '(?P<month>\d{1,2})/'
               '(?P<day>\d{1,2})/$',
        view=Teacher_family_detailDayArchiveView.as_view(),
        name='teacher_teacher_family_detail_day_archive'
    ),
    url(
        regex=r'^teacher_family_detail/(?P<pk>\d+?)/delete/$',
        view=Teacher_family_detailDeleteView.as_view(),
        name='teacher_teacher_family_detail_delete'
    ),
    url(
        regex=r'^teacher_family_detail/(?P<pk>\d+?)/$',
        view=Teacher_family_detailDetailView.as_view(),
        name='teacher_teacher_family_detail_detail'
    ),
    url(
        regex=r'^teacher_family_detail/$',
        view=Teacher_family_detailListView.as_view(),
        name='teacher_teacher_family_detail_list'
    ),
    url(
        regex=r'^teacher_family_detail/archive/(?P<year>\d{4})/'
               '(?P<month>\d{1,2})/$',
        view=Teacher_family_detailMonthArchiveView.as_view(),
        name='teacher_teacher_family_detail_month_archive'
    ),
    url(
        regex=r'^teacher_family_detail/today/$',
        view=Teacher_family_detailTodayArchiveView.as_view(),
        name='teacher_teacher_family_detail_today_archive'
    ),
    url(
        regex=r'^teacher_family_detail/(?P<pk>\d+?)/update/$',
        view=Teacher_family_detailUpdateView.as_view(),
        name='teacher_teacher_family_detail_update'
    ),
    url(
        regex=r'^teacher_family_detail/archive/(?P<year>\d{4})/'
               '(?P<month>\d{1,2})/'
               'week/(?P<week>\d{1,2})/$',
        view=Teacher_family_detailWeekArchiveView.as_view(),
        name='teacher_teacher_family_detail_week_archive'
    ),
    url(
        regex=r'^teacher_family_detail/archive/(?P<year>\d{4})/$',
        view=Teacher_family_detailYearArchiveView.as_view(),
        name='teacher_teacher_family_detail_year_archive'
    ),
)


from teacher.views.teacher_immovalble_property_views import *
urlpatterns += patterns('',
    url(
        regex=r'^teacher_immovalble_property/archive/$',
        view=Teacher_immovalble_propertyArchiveIndexView.as_view(),
        name='teacher_teacher_immovalble_property_archive_index'
    ),
    url(
        regex=r'^teacher_immovalble_property/create/$',
        view=Teacher_immovalble_propertyCreateView.as_view(),
        name='teacher_teacher_immovalble_property_create'
    ),
    url(
        regex=r'^teacher_immovalble_property/(?P<year>\d{4})/'
               '(?P<month>\d{1,2})/'
               '(?P<day>\d{1,2})/'
               '(?P<pk>\d+?)/$',
        view=Teacher_immovalble_propertyDateDetailView.as_view(),
        name='teacher_teacher_immovalble_property_date_detail'
    ),
    url(
        regex=r'^teacher_immovalble_property/archive/(?P<year>\d{4})/'
               '(?P<month>\d{1,2})/'
               '(?P<day>\d{1,2})/$',
        view=Teacher_immovalble_propertyDayArchiveView.as_view(),
        name='teacher_teacher_immovalble_property_day_archive'
    ),
    url(
        regex=r'^teacher_immovalble_property/(?P<pk>\d+?)/delete/$',
        view=Teacher_immovalble_propertyDeleteView.as_view(),
        name='teacher_teacher_immovalble_property_delete'
    ),
    url(
        regex=r'^teacher_immovalble_property/(?P<pk>\d+?)/$',
        view=Teacher_immovalble_propertyDetailView.as_view(),
        name='teacher_teacher_immovalble_property_detail'
    ),
    url(
        regex=r'^teacher_immovalble_property/$',
        view=Teacher_immovalble_propertyListView.as_view(),
        name='teacher_teacher_immovalble_property_list'
    ),
    url(
        regex=r'^teacher_immovalble_property/archive/(?P<year>\d{4})/'
               '(?P<month>\d{1,2})/$',
        view=Teacher_immovalble_propertyMonthArchiveView.as_view(),
        name='teacher_teacher_immovalble_property_month_archive'
    ),
    url(
        regex=r'^teacher_immovalble_property/today/$',
        view=Teacher_immovalble_propertyTodayArchiveView.as_view(),
        name='teacher_teacher_immovalble_property_today_archive'
    ),
    url(
        regex=r'^teacher_immovalble_property/(?P<pk>\d+?)/update/$',
        view=Teacher_immovalble_propertyUpdateView.as_view(),
        name='teacher_teacher_immovalble_property_update'
    ),
    url(
        regex=r'^teacher_immovalble_property/archive/(?P<year>\d{4})/'
               '(?P<month>\d{1,2})/'
               'week/(?P<week>\d{1,2})/$',
        view=Teacher_immovalble_propertyWeekArchiveView.as_view(),
        name='teacher_teacher_immovalble_property_week_archive'
    ),
    url(
        regex=r'^teacher_immovalble_property/archive/(?P<year>\d{4})/$',
        view=Teacher_immovalble_propertyYearArchiveView.as_view(),
        name='teacher_teacher_immovalble_property_year_archive'
    ),
)


from teacher.views.teacher_movable_property_views import *
urlpatterns += patterns('',
    url(
        regex=r'^teacher_movable_property/archive/$',
        view=Teacher_movable_propertyArchiveIndexView.as_view(),
        name='teacher_teacher_movable_property_archive_index'
    ),
    url(
        regex=r'^teacher_movable_property/create/$',
        view=Teacher_movable_propertyCreateView.as_view(),
        name='teacher_teacher_movable_property_create'
    ),
    url(
        regex=r'^teacher_movable_property/(?P<year>\d{4})/'
               '(?P<month>\d{1,2})/'
               '(?P<day>\d{1,2})/'
               '(?P<pk>\d+?)/$',
        view=Teacher_movable_propertyDateDetailView.as_view(),
        name='teacher_teacher_movable_property_date_detail'
    ),
    url(
        regex=r'^teacher_movable_property/archive/(?P<year>\d{4})/'
               '(?P<month>\d{1,2})/'
               '(?P<day>\d{1,2})/$',
        view=Teacher_movable_propertyDayArchiveView.as_view(),
        name='teacher_teacher_movable_property_day_archive'
    ),
    url(
        regex=r'^teacher_movable_property/(?P<pk>\d+?)/delete/$',
        view=Teacher_movable_propertyDeleteView.as_view(),
        name='teacher_teacher_movable_property_delete'
    ),
    url(
        regex=r'^teacher_movable_property/(?P<pk>\d+?)/$',
        view=Teacher_movable_propertyDetailView.as_view(),
        name='teacher_teacher_movable_property_detail'
    ),
    url(
        regex=r'^teacher_movable_property/$',
        view=Teacher_movable_propertyListView.as_view(),
        name='teacher_teacher_movable_property_list'
    ),
    url(
        regex=r'^teacher_movable_property/archive/(?P<year>\d{4})/'
               '(?P<month>\d{1,2})/$',
        view=Teacher_movable_propertyMonthArchiveView.as_view(),
        name='teacher_teacher_movable_property_month_archive'
    ),
    url(
        regex=r'^teacher_movable_property/today/$',
        view=Teacher_movable_propertyTodayArchiveView.as_view(),
        name='teacher_teacher_movable_property_today_archive'
    ),
    url(
        regex=r'^teacher_movable_property/(?P<pk>\d+?)/update/$',
        view=Teacher_movable_propertyUpdateView.as_view(),
        name='teacher_teacher_movable_property_update'
    ),
    url(
        regex=r'^teacher_movable_property/archive/(?P<year>\d{4})/'
               '(?P<month>\d{1,2})/'
               'week/(?P<week>\d{1,2})/$',
        view=Teacher_movable_propertyWeekArchiveView.as_view(),
        name='teacher_teacher_movable_property_week_archive'
    ),
    url(
        regex=r'^teacher_movable_property/archive/(?P<year>\d{4})/$',
        view=Teacher_movable_propertyYearArchiveView.as_view(),
        name='teacher_teacher_movable_property_year_archive'
    ),
)


from teacher.views.teacher_education_views import *
urlpatterns += patterns('',
    url(
        regex=r'^teacher_education/archive/$',
        view=Teacher_educationArchiveIndexView.as_view(),
        name='teacher_teacher_education_archive_index'
    ),
    url(
        regex=r'^teacher_education/create/$',
        view=Teacher_educationCreateView.as_view(),
        name='teacher_teacher_education_create'
    ),
    url(
        regex=r'^teacher_education/(?P<year>\d{4})/'
               '(?P<month>\d{1,2})/'
               '(?P<day>\d{1,2})/'
               '(?P<pk>\d+?)/$',
        view=Teacher_educationDateDetailView.as_view(),
        name='teacher_teacher_education_date_detail'
    ),
    url(
        regex=r'^teacher_education/archive/(?P<year>\d{4})/'
               '(?P<month>\d{1,2})/'
               '(?P<day>\d{1,2})/$',
        view=Teacher_educationDayArchiveView.as_view(),
        name='teacher_teacher_education_day_archive'
    ),
    url(
        regex=r'^teacher_education/(?P<pk>\d+?)/delete/$',
        view=Teacher_educationDeleteView.as_view(),
        name='teacher_teacher_education_delete'
    ),
    url(
        regex=r'^teacher_education/(?P<pk>\d+?)/$',
        view=Teacher_educationDetailView.as_view(),
        name='teacher_teacher_education_detail'
    ),
    url(
        regex=r'^teacher_education/$',
        view=Teacher_educationListView.as_view(),
        name='teacher_teacher_education_list'
    ),
    url(
        regex=r'^teacher_education/archive/(?P<year>\d{4})/'
               '(?P<month>\d{1,2})/$',
        view=Teacher_educationMonthArchiveView.as_view(),
        name='teacher_teacher_education_month_archive'
    ),
    url(
        regex=r'^teacher_education/today/$',
        view=Teacher_educationTodayArchiveView.as_view(),
        name='teacher_teacher_education_today_archive'
    ),
    url(
        regex=r'^teacher_education/(?P<pk>\d+?)/update/$',
        view=Teacher_educationUpdateView.as_view(),
        name='teacher_teacher_education_update'
    ),
    url(
        regex=r'^teacher_education/archive/(?P<year>\d{4})/'
               '(?P<month>\d{1,2})/'
               'week/(?P<week>\d{1,2})/$',
        view=Teacher_educationWeekArchiveView.as_view(),
        name='teacher_teacher_education_week_archive'
    ),
    url(
        regex=r'^teacher_education/archive/(?P<year>\d{4})/$',
        view=Teacher_educationYearArchiveView.as_view(),
        name='teacher_teacher_education_year_archive'
    ),
)


from teacher.views.teacher_test_views import *
urlpatterns += patterns('',
    url(
        regex=r'^teacher_test/archive/$',
        view=Teacher_testArchiveIndexView.as_view(),
        name='teacher_teacher_test_archive_index'
    ),
    url(
        regex=r'^teacher_test/create/$',
        view=Teacher_testCreateView.as_view(),
        name='teacher_teacher_test_create'
    ),
    url(
        regex=r'^teacher_test/(?P<year>\d{4})/'
               '(?P<month>\d{1,2})/'
               '(?P<day>\d{1,2})/'
               '(?P<pk>\d+?)/$',
        view=Teacher_testDateDetailView.as_view(),
        name='teacher_teacher_test_date_detail'
    ),
    url(
        regex=r'^teacher_test/archive/(?P<year>\d{4})/'
               '(?P<month>\d{1,2})/'
               '(?P<day>\d{1,2})/$',
        view=Teacher_testDayArchiveView.as_view(),
        name='teacher_teacher_test_day_archive'
    ),
    url(
        regex=r'^teacher_test/(?P<pk>\d+?)/delete/$',
        view=Teacher_testDeleteView.as_view(),
        name='teacher_teacher_test_delete'
    ),
    url(
        regex=r'^teacher_test/(?P<pk>\d+?)/$',
        view=Teacher_testDetailView.as_view(),
        name='teacher_teacher_test_detail'
    ),
    url(
        regex=r'^teacher_test/$',
        view=Teacher_testListView.as_view(),
        name='teacher_teacher_test_list'
    ),
    url(
        regex=r'^teacher_test/archive/(?P<year>\d{4})/'
               '(?P<month>\d{1,2})/$',
        view=Teacher_testMonthArchiveView.as_view(),
        name='teacher_teacher_test_month_archive'
    ),
    url(
        regex=r'^teacher_test/today/$',
        view=Teacher_testTodayArchiveView.as_view(),
        name='teacher_teacher_test_today_archive'
    ),
    url(
        regex=r'^teacher_test/(?P<pk>\d+?)/update/$',
        view=Teacher_testUpdateView.as_view(),
        name='teacher_teacher_test_update'
    ),
    url(
        regex=r'^teacher_test/archive/(?P<year>\d{4})/'
               '(?P<month>\d{1,2})/'
               'week/(?P<week>\d{1,2})/$',
        view=Teacher_testWeekArchiveView.as_view(),
        name='teacher_teacher_test_week_archive'
    ),
    url(
        regex=r'^teacher_test/archive/(?P<year>\d{4})/$',
        view=Teacher_testYearArchiveView.as_view(),
        name='teacher_teacher_test_year_archive'
    ),
)


from teacher.views.teacher_training_views import *
urlpatterns += patterns('',
    url(
        regex=r'^teacher_training/archive/$',
        view=Teacher_trainingArchiveIndexView.as_view(),
        name='teacher_teacher_training_archive_index'
    ),
    url(
        regex=r'^teacher_training/create/$',
        view=Teacher_trainingCreateView.as_view(),
        name='teacher_teacher_training_create'
    ),
    url(
        regex=r'^teacher_training/(?P<year>\d{4})/'
               '(?P<month>\d{1,2})/'
               '(?P<day>\d{1,2})/'
               '(?P<pk>\d+?)/$',
        view=Teacher_trainingDateDetailView.as_view(),
        name='teacher_teacher_training_date_detail'
    ),
    url(
        regex=r'^teacher_training/archive/(?P<year>\d{4})/'
               '(?P<month>\d{1,2})/'
               '(?P<day>\d{1,2})/$',
        view=Teacher_trainingDayArchiveView.as_view(),
        name='teacher_teacher_training_day_archive'
    ),
    url(
        regex=r'^teacher_training/(?P<pk>\d+?)/delete/$',
        view=Teacher_trainingDeleteView.as_view(),
        name='teacher_teacher_training_delete'
    ),
    url(
        regex=r'^teacher_training/(?P<pk>\d+?)/$',
        view=Teacher_trainingDetailView.as_view(),
        name='teacher_teacher_training_detail'
    ),
    url(
        regex=r'^teacher_training/$',
        view=Teacher_trainingListView.as_view(),
        name='teacher_teacher_training_list'
    ),
    url(
        regex=r'^teacher_training/archive/(?P<year>\d{4})/'
               '(?P<month>\d{1,2})/$',
        view=Teacher_trainingMonthArchiveView.as_view(),
        name='teacher_teacher_training_month_archive'
    ),
    url(
        regex=r'^teacher_training/today/$',
        view=Teacher_trainingTodayArchiveView.as_view(),
        name='teacher_teacher_training_today_archive'
    ),
    url(
        regex=r'^teacher_training/(?P<pk>\d+?)/update/$',
        view=Teacher_trainingUpdateView.as_view(),
        name='teacher_teacher_training_update'
    ),
    url(
        regex=r'^teacher_training/archive/(?P<year>\d{4})/'
               '(?P<month>\d{1,2})/'
               'week/(?P<week>\d{1,2})/$',
        view=Teacher_trainingWeekArchiveView.as_view(),
        name='teacher_teacher_training_week_archive'
    ),
    url(
        regex=r'^teacher_training/archive/(?P<year>\d{4})/$',
        view=Teacher_trainingYearArchiveView.as_view(),
        name='teacher_teacher_training_year_archive'
    ),
)


from teacher.views.teacher_post_views import *
urlpatterns += patterns('',
    url(
        regex=r'^teacher_post/archive/$',
        view=Teacher_postArchiveIndexView.as_view(),
        name='teacher_teacher_post_archive_index'
    ),
    url(
        regex=r'^teacher_post/create/$',
        view=Teacher_postCreateView.as_view(),
        name='teacher_teacher_post_create'
    ),
    url(
        regex=r'^teacher_post/(?P<year>\d{4})/'
               '(?P<month>\d{1,2})/'
               '(?P<day>\d{1,2})/'
               '(?P<pk>\d+?)/$',
        view=Teacher_postDateDetailView.as_view(),
        name='teacher_teacher_post_date_detail'
    ),
    url(
        regex=r'^teacher_post/archive/(?P<year>\d{4})/'
               '(?P<month>\d{1,2})/'
               '(?P<day>\d{1,2})/$',
        view=Teacher_postDayArchiveView.as_view(),
        name='teacher_teacher_post_day_archive'
    ),
    url(
        regex=r'^teacher_post/(?P<pk>\d+?)/delete/$',
        view=Teacher_postDeleteView.as_view(),
        name='teacher_teacher_post_delete'
    ),
    url(
        regex=r'^teacher_post/(?P<pk>\d+?)/$',
        view=Teacher_postDetailView.as_view(),
        name='teacher_teacher_post_detail'
    ),
    url(
        regex=r'^teacher_post/$',
        view=Teacher_postListView.as_view(),
        name='teacher_teacher_post_list'
    ),
    url(
        regex=r'^teacher_post/archive/(?P<year>\d{4})/'
               '(?P<month>\d{1,2})/$',
        view=Teacher_postMonthArchiveView.as_view(),
        name='teacher_teacher_post_month_archive'
    ),
    url(
        regex=r'^teacher_post/today/$',
        view=Teacher_postTodayArchiveView.as_view(),
        name='teacher_teacher_post_today_archive'
    ),
    url(
        regex=r'^teacher_post/(?P<pk>\d+?)/update/$',
        view=Teacher_postUpdateView.as_view(),
        name='teacher_teacher_post_update'
    ),
    url(
        regex=r'^teacher_post/archive/(?P<year>\d{4})/'
               '(?P<month>\d{1,2})/'
               'week/(?P<week>\d{1,2})/$',
        view=Teacher_postWeekArchiveView.as_view(),
        name='teacher_teacher_post_week_archive'
    ),
    url(
        regex=r'^teacher_post/archive/(?P<year>\d{4})/$',
        view=Teacher_postYearArchiveView.as_view(),
        name='teacher_teacher_post_year_archive'
    ),
)


from teacher.views.teacher_professional_views import *
urlpatterns += patterns('',
    url(
        regex=r'^teacher_professional/archive/$',
        view=Teacher_professionalArchiveIndexView.as_view(),
        name='teacher_teacher_professional_archive_index'
    ),
    url(
        regex=r'^teacher_professional/create/$',
        view=Teacher_professionalCreateView.as_view(),
        name='teacher_teacher_professional_create'
    ),
    url(
        regex=r'^teacher_professional/(?P<year>\d{4})/'
               '(?P<month>\d{1,2})/'
               '(?P<day>\d{1,2})/'
               '(?P<pk>\d+?)/$',
        view=Teacher_professionalDateDetailView.as_view(),
        name='teacher_teacher_professional_date_detail'
    ),
    url(
        regex=r'^teacher_professional/archive/(?P<year>\d{4})/'
               '(?P<month>\d{1,2})/'
               '(?P<day>\d{1,2})/$',
        view=Teacher_professionalDayArchiveView.as_view(),
        name='teacher_teacher_professional_day_archive'
    ),
    url(
        regex=r'^teacher_professional/(?P<pk>\d+?)/delete/$',
        view=Teacher_professionalDeleteView.as_view(),
        name='teacher_teacher_professional_delete'
    ),
    url(
        regex=r'^teacher_professional/(?P<pk>\d+?)/$',
        view=Teacher_professionalDetailView.as_view(),
        name='teacher_teacher_professional_detail'
    ),
    url(
        regex=r'^teacher_professional/$',
        view=Teacher_professionalListView.as_view(),
        name='teacher_teacher_professional_list'
    ),
    url(
        regex=r'^teacher_professional/archive/(?P<year>\d{4})/'
               '(?P<month>\d{1,2})/$',
        view=Teacher_professionalMonthArchiveView.as_view(),
        name='teacher_teacher_professional_month_archive'
    ),
    url(
        regex=r'^teacher_professional/today/$',
        view=Teacher_professionalTodayArchiveView.as_view(),
        name='teacher_teacher_professional_today_archive'
    ),
    url(
        regex=r'^teacher_professional/(?P<pk>\d+?)/update/$',
        view=Teacher_professionalUpdateView.as_view(),
        name='teacher_teacher_professional_update'
    ),
    url(
        regex=r'^teacher_professional/archive/(?P<year>\d{4})/'
               '(?P<month>\d{1,2})/'
               'week/(?P<week>\d{1,2})/$',
        view=Teacher_professionalWeekArchiveView.as_view(),
        name='teacher_teacher_professional_week_archive'
    ),
    url(
        regex=r'^teacher_professional/archive/(?P<year>\d{4})/$',
        view=Teacher_professionalYearArchiveView.as_view(),
        name='teacher_teacher_professional_year_archive'
    ),
)


from teacher.views.teacher_leave_surrender_views import *
urlpatterns += patterns('',
    url(
        regex=r'^teacher_leave_surrender/archive/$',
        view=Teacher_leave_surrenderArchiveIndexView.as_view(),
        name='teacher_teacher_leave_surrender_archive_index'
    ),
    url(
        regex=r'^teacher_leave_surrender/create/$',
        view=Teacher_leave_surrenderCreateView.as_view(),
        name='teacher_teacher_leave_surrender_create'
    ),
    url(
        regex=r'^teacher_leave_surrender/(?P<year>\d{4})/'
               '(?P<month>\d{1,2})/'
               '(?P<day>\d{1,2})/'
               '(?P<pk>\d+?)/$',
        view=Teacher_leave_surrenderDateDetailView.as_view(),
        name='teacher_teacher_leave_surrender_date_detail'
    ),
    url(
        regex=r'^teacher_leave_surrender/archive/(?P<year>\d{4})/'
               '(?P<month>\d{1,2})/'
               '(?P<day>\d{1,2})/$',
        view=Teacher_leave_surrenderDayArchiveView.as_view(),
        name='teacher_teacher_leave_surrender_day_archive'
    ),
    url(
        regex=r'^teacher_leave_surrender/(?P<pk>\d+?)/delete/$',
        view=Teacher_leave_surrenderDeleteView.as_view(),
        name='teacher_teacher_leave_surrender_delete'
    ),
    url(
        regex=r'^teacher_leave_surrender/(?P<pk>\d+?)/$',
        view=Teacher_leave_surrenderDetailView.as_view(),
        name='teacher_teacher_leave_surrender_detail'
    ),
    url(
        regex=r'^teacher_leave_surrender/$',
        view=Teacher_leave_surrenderListView.as_view(),
        name='teacher_teacher_leave_surrender_list'
    ),
    url(
        regex=r'^teacher_leave_surrender/archive/(?P<year>\d{4})/'
               '(?P<month>\d{1,2})/$',
        view=Teacher_leave_surrenderMonthArchiveView.as_view(),
        name='teacher_teacher_leave_surrender_month_archive'
    ),
    url(
        regex=r'^teacher_leave_surrender/today/$',
        view=Teacher_leave_surrenderTodayArchiveView.as_view(),
        name='teacher_teacher_leave_surrender_today_archive'
    ),
    url(
        regex=r'^teacher_leave_surrender/(?P<pk>\d+?)/update/$',
        view=Teacher_leave_surrenderUpdateView.as_view(),
        name='teacher_teacher_leave_surrender_update'
    ),
    url(
        regex=r'^teacher_leave_surrender/archive/(?P<year>\d{4})/'
               '(?P<month>\d{1,2})/'
               'week/(?P<week>\d{1,2})/$',
        view=Teacher_leave_surrenderWeekArchiveView.as_view(),
        name='teacher_teacher_leave_surrender_week_archive'
    ),
    url(
        regex=r'^teacher_leave_surrender/archive/(?P<year>\d{4})/$',
        view=Teacher_leave_surrenderYearArchiveView.as_view(),
        name='teacher_teacher_leave_surrender_year_archive'
    ),
)


from teacher.views.teacher_leave_views import *
urlpatterns += patterns('',
    url(
        regex=r'^teacher_leave/archive/$',
        view=Teacher_leaveArchiveIndexView.as_view(),
        name='teacher_teacher_leave_archive_index'
    ),
    url(
        regex=r'^teacher_leave/create/$',
        view=Teacher_leaveCreateView.as_view(),
        name='teacher_teacher_leave_create'
    ),
    url(
        regex=r'^teacher_leave/(?P<year>\d{4})/'
               '(?P<month>\d{1,2})/'
               '(?P<day>\d{1,2})/'
               '(?P<pk>\d+?)/$',
        view=Teacher_leaveDateDetailView.as_view(),
        name='teacher_teacher_leave_date_detail'
    ),
    url(
        regex=r'^teacher_leave/archive/(?P<year>\d{4})/'
               '(?P<month>\d{1,2})/'
               '(?P<day>\d{1,2})/$',
        view=Teacher_leaveDayArchiveView.as_view(),
        name='teacher_teacher_leave_day_archive'
    ),
    url(
        regex=r'^teacher_leave/(?P<pk>\d+?)/delete/$',
        view=Teacher_leaveDeleteView.as_view(),
        name='teacher_teacher_leave_delete'
    ),
    url(
        regex=r'^teacher_leave/(?P<pk>\d+?)/$',
        view=Teacher_leaveDetailView.as_view(),
        name='teacher_teacher_leave_detail'
    ),
    url(
        regex=r'^teacher_leave/$',
        view=Teacher_leaveListView.as_view(),
        name='teacher_teacher_leave_list'
    ),
    url(
        regex=r'^teacher_leave/archive/(?P<year>\d{4})/'
               '(?P<month>\d{1,2})/$',
        view=Teacher_leaveMonthArchiveView.as_view(),
        name='teacher_teacher_leave_month_archive'
    ),
    url(
        regex=r'^teacher_leave/today/$',
        view=Teacher_leaveTodayArchiveView.as_view(),
        name='teacher_teacher_leave_today_archive'
    ),
    url(
        regex=r'^teacher_leave/(?P<pk>\d+?)/update/$',
        view=Teacher_leaveUpdateView.as_view(),
        name='teacher_teacher_leave_update'
    ),
    url(
        regex=r'^teacher_leave/archive/(?P<year>\d{4})/'
               '(?P<month>\d{1,2})/'
               'week/(?P<week>\d{1,2})/$',
        view=Teacher_leaveWeekArchiveView.as_view(),
        name='teacher_teacher_leave_week_archive'
    ),
    url(
        regex=r'^teacher_leave/archive/(?P<year>\d{4})/$',
        view=Teacher_leaveYearArchiveView.as_view(),
        name='teacher_teacher_leave_year_archive'
    ),
)


from teacher.views.teacher_ltc_views import *
urlpatterns += patterns('',
    url(
        regex=r'^teacher_ltc/archive/$',
        view=Teacher_ltcArchiveIndexView.as_view(),
        name='teacher_teacher_ltc_archive_index'
    ),
    url(
        regex=r'^teacher_ltc/create/$',
        view=Teacher_ltcCreateView.as_view(),
        name='teacher_teacher_ltc_create'
    ),
    url(
        regex=r'^teacher_ltc/(?P<year>\d{4})/'
               '(?P<month>\d{1,2})/'
               '(?P<day>\d{1,2})/'
               '(?P<pk>\d+?)/$',
        view=Teacher_ltcDateDetailView.as_view(),
        name='teacher_teacher_ltc_date_detail'
    ),
    url(
        regex=r'^teacher_ltc/archive/(?P<year>\d{4})/'
               '(?P<month>\d{1,2})/'
               '(?P<day>\d{1,2})/$',
        view=Teacher_ltcDayArchiveView.as_view(),
        name='teacher_teacher_ltc_day_archive'
    ),
    url(
        regex=r'^teacher_ltc/(?P<pk>\d+?)/delete/$',
        view=Teacher_ltcDeleteView.as_view(),
        name='teacher_teacher_ltc_delete'
    ),
    url(
        regex=r'^teacher_ltc/(?P<pk>\d+?)/$',
        view=Teacher_ltcDetailView.as_view(),
        name='teacher_teacher_ltc_detail'
    ),
    url(
        regex=r'^teacher_ltc/$',
        view=Teacher_ltcListView.as_view(),
        name='teacher_teacher_ltc_list'
    ),
    url(
        regex=r'^teacher_ltc/archive/(?P<year>\d{4})/'
               '(?P<month>\d{1,2})/$',
        view=Teacher_ltcMonthArchiveView.as_view(),
        name='teacher_teacher_ltc_month_archive'
    ),
    url(
        regex=r'^teacher_ltc/today/$',
        view=Teacher_ltcTodayArchiveView.as_view(),
        name='teacher_teacher_ltc_today_archive'
    ),
    url(
        regex=r'^teacher_ltc/(?P<pk>\d+?)/update/$',
        view=Teacher_ltcUpdateView.as_view(),
        name='teacher_teacher_ltc_update'
    ),
    url(
        regex=r'^teacher_ltc/archive/(?P<year>\d{4})/'
               '(?P<month>\d{1,2})/'
               'week/(?P<week>\d{1,2})/$',
        view=Teacher_ltcWeekArchiveView.as_view(),
        name='teacher_teacher_ltc_week_archive'
    ),
    url(
        regex=r'^teacher_ltc/archive/(?P<year>\d{4})/$',
        view=Teacher_ltcYearArchiveView.as_view(),
        name='teacher_teacher_ltc_year_archive'
    ),
)


from teacher.views.teacher_leave_credit_views import *
urlpatterns += patterns('',
    url(
        regex=r'^teacher_leave_credit/archive/$',
        view=Teacher_leave_creditArchiveIndexView.as_view(),
        name='teacher_teacher_leave_credit_archive_index'
    ),
    url(
        regex=r'^teacher_leave_credit/create/$',
        view=Teacher_leave_creditCreateView.as_view(),
        name='teacher_teacher_leave_credit_create'
    ),
    url(
        regex=r'^teacher_leave_credit/(?P<year>\d{4})/'
               '(?P<month>\d{1,2})/'
               '(?P<day>\d{1,2})/'
               '(?P<pk>\d+?)/$',
        view=Teacher_leave_creditDateDetailView.as_view(),
        name='teacher_teacher_leave_credit_date_detail'
    ),
    url(
        regex=r'^teacher_leave_credit/archive/(?P<year>\d{4})/'
               '(?P<month>\d{1,2})/'
               '(?P<day>\d{1,2})/$',
        view=Teacher_leave_creditDayArchiveView.as_view(),
        name='teacher_teacher_leave_credit_day_archive'
    ),
    url(
        regex=r'^teacher_leave_credit/(?P<pk>\d+?)/delete/$',
        view=Teacher_leave_creditDeleteView.as_view(),
        name='teacher_teacher_leave_credit_delete'
    ),
    url(
        regex=r'^teacher_leave_credit/(?P<pk>\d+?)/$',
        view=Teacher_leave_creditDetailView.as_view(),
        name='teacher_teacher_leave_credit_detail'
    ),
    url(
        regex=r'^teacher_leave_credit/$',
        view=Teacher_leave_creditListView.as_view(),
        name='teacher_teacher_leave_credit_list'
    ),
    url(
        regex=r'^teacher_leave_credit/archive/(?P<year>\d{4})/'
               '(?P<month>\d{1,2})/$',
        view=Teacher_leave_creditMonthArchiveView.as_view(),
        name='teacher_teacher_leave_credit_month_archive'
    ),
    url(
        regex=r'^teacher_leave_credit/today/$',
        view=Teacher_leave_creditTodayArchiveView.as_view(),
        name='teacher_teacher_leave_credit_today_archive'
    ),
    url(
        regex=r'^teacher_leave_credit/(?P<pk>\d+?)/update/$',
        view=Teacher_leave_creditUpdateView.as_view(),
        name='teacher_teacher_leave_credit_update'
    ),
    url(
        regex=r'^teacher_leave_credit/archive/(?P<year>\d{4})/'
               '(?P<month>\d{1,2})/'
               'week/(?P<week>\d{1,2})/$',
        view=Teacher_leave_creditWeekArchiveView.as_view(),
        name='teacher_teacher_leave_credit_week_archive'
    ),
    url(
        regex=r'^teacher_leave_credit/archive/(?P<year>\d{4})/$',
        view=Teacher_leave_creditYearArchiveView.as_view(),
        name='teacher_teacher_leave_credit_year_archive'
    ),
)


from teacher.views.teacher_previous_employment_views import *
urlpatterns += patterns('',
    url(
        regex=r'^teacher_previous_employment/archive/$',
        view=Teacher_previous_employmentArchiveIndexView.as_view(),
        name='teacher_teacher_previous_employment_archive_index'
    ),
    url(
        regex=r'^teacher_previous_employment/create/$',
        view=Teacher_previous_employmentCreateView.as_view(),
        name='teacher_teacher_previous_employment_create'
    ),
    url(
        regex=r'^teacher_previous_employment/(?P<year>\d{4})/'
               '(?P<month>\d{1,2})/'
               '(?P<day>\d{1,2})/'
               '(?P<pk>\d+?)/$',
        view=Teacher_previous_employmentDateDetailView.as_view(),
        name='teacher_teacher_previous_employment_date_detail'
    ),
    url(
        regex=r'^teacher_previous_employment/archive/(?P<year>\d{4})/'
               '(?P<month>\d{1,2})/'
               '(?P<day>\d{1,2})/$',
        view=Teacher_previous_employmentDayArchiveView.as_view(),
        name='teacher_teacher_previous_employment_day_archive'
    ),
    url(
        regex=r'^teacher_previous_employment/(?P<pk>\d+?)/delete/$',
        view=Teacher_previous_employmentDeleteView.as_view(),
        name='teacher_teacher_previous_employment_delete'
    ),
    url(
        regex=r'^teacher_previous_employment/(?P<pk>\d+?)/$',
        view=Teacher_previous_employmentDetailView.as_view(),
        name='teacher_teacher_previous_employment_detail'
    ),
    url(
        regex=r'^teacher_previous_employment/$',
        view=Teacher_previous_employmentListView.as_view(),
        name='teacher_teacher_previous_employment_list'
    ),
    url(
        regex=r'^teacher_previous_employment/archive/(?P<year>\d{4})/'
               '(?P<month>\d{1,2})/$',
        view=Teacher_previous_employmentMonthArchiveView.as_view(),
        name='teacher_teacher_previous_employment_month_archive'
    ),
    url(
        regex=r'^teacher_previous_employment/today/$',
        view=Teacher_previous_employmentTodayArchiveView.as_view(),
        name='teacher_teacher_previous_employment_today_archive'
    ),
    url(
        regex=r'^teacher_previous_employment/(?P<pk>\d+?)/update/$',
        view=Teacher_previous_employmentUpdateView.as_view(),
        name='teacher_teacher_previous_employment_update'
    ),
    url(
        regex=r'^teacher_previous_employment/archive/(?P<year>\d{4})/'
               '(?P<month>\d{1,2})/'
               'week/(?P<week>\d{1,2})/$',
        view=Teacher_previous_employmentWeekArchiveView.as_view(),
        name='teacher_teacher_previous_employment_week_archive'
    ),
    url(
        regex=r'^teacher_previous_employment/archive/(?P<year>\d{4})/$',
        view=Teacher_previous_employmentYearArchiveView.as_view(),
        name='teacher_teacher_previous_employment_year_archive'
    ),
)


from teacher.views.teacher_loan_views import *
urlpatterns += patterns('',
    url(
        regex=r'^teacher_loan/archive/$',
        view=Teacher_loanArchiveIndexView.as_view(),
        name='teacher_teacher_loan_archive_index'
    ),
    url(
        regex=r'^teacher_loan/create/$',
        view=Teacher_loanCreateView.as_view(),
        name='teacher_teacher_loan_create'
    ),
    url(
        regex=r'^teacher_loan/(?P<year>\d{4})/'
               '(?P<month>\d{1,2})/'
               '(?P<day>\d{1,2})/'
               '(?P<pk>\d+?)/$',
        view=Teacher_loanDateDetailView.as_view(),
        name='teacher_teacher_loan_date_detail'
    ),
    url(
        regex=r'^teacher_loan/archive/(?P<year>\d{4})/'
               '(?P<month>\d{1,2})/'
               '(?P<day>\d{1,2})/$',
        view=Teacher_loanDayArchiveView.as_view(),
        name='teacher_teacher_loan_day_archive'
    ),
    url(
        regex=r'^teacher_loan/(?P<pk>\d+?)/delete/$',
        view=Teacher_loanDeleteView.as_view(),
        name='teacher_teacher_loan_delete'
    ),
    url(
        regex=r'^teacher_loan/(?P<pk>\d+?)/$',
        view=Teacher_loanDetailView.as_view(),
        name='teacher_teacher_loan_detail'
    ),
    url(
        regex=r'^teacher_loan/$',
        view=Teacher_loanListView.as_view(),
        name='teacher_teacher_loan_list'
    ),
    url(
        regex=r'^teacher_loan/archive/(?P<year>\d{4})/'
               '(?P<month>\d{1,2})/$',
        view=Teacher_loanMonthArchiveView.as_view(),
        name='teacher_teacher_loan_month_archive'
    ),
    url(
        regex=r'^teacher_loan/today/$',
        view=Teacher_loanTodayArchiveView.as_view(),
        name='teacher_teacher_loan_today_archive'
    ),
    url(
        regex=r'^teacher_loan/(?P<pk>\d+?)/update/$',
        view=Teacher_loanUpdateView.as_view(),
        name='teacher_teacher_loan_update'
    ),
    url(
        regex=r'^teacher_loan/archive/(?P<year>\d{4})/'
               '(?P<month>\d{1,2})/'
               'week/(?P<week>\d{1,2})/$',
        view=Teacher_loanWeekArchiveView.as_view(),
        name='teacher_teacher_loan_week_archive'
    ),
    url(
        regex=r'^teacher_loan/archive/(?P<year>\d{4})/$',
        view=Teacher_loanYearArchiveView.as_view(),
        name='teacher_teacher_loan_year_archive'
    ),
)


from teacher.views.teacher_nomini_views import *
urlpatterns += patterns('',
    url(
        regex=r'^teacher_nomini/archive/$',
        view=Teacher_nominiArchiveIndexView.as_view(),
        name='teacher_teacher_nomini_archive_index'
    ),
    url(
        regex=r'^teacher_nomini/create/$',
        view=Teacher_nominiCreateView.as_view(),
        name='teacher_teacher_nomini_create'
    ),
    url(
        regex=r'^teacher_nomini/(?P<year>\d{4})/'
               '(?P<month>\d{1,2})/'
               '(?P<day>\d{1,2})/'
               '(?P<pk>\d+?)/$',
        view=Teacher_nominiDateDetailView.as_view(),
        name='teacher_teacher_nomini_date_detail'
    ),
    url(
        regex=r'^teacher_nomini/archive/(?P<year>\d{4})/'
               '(?P<month>\d{1,2})/'
               '(?P<day>\d{1,2})/$',
        view=Teacher_nominiDayArchiveView.as_view(),
        name='teacher_teacher_nomini_day_archive'
    ),
    url(
        regex=r'^teacher_nomini/(?P<pk>\d+?)/delete/$',
        view=Teacher_nominiDeleteView.as_view(),
        name='teacher_teacher_nomini_delete'
    ),
    url(
        regex=r'^teacher_nomini/(?P<pk>\d+?)/$',
        view=Teacher_nominiDetailView.as_view(),
        name='teacher_teacher_nomini_detail'
    ),
    url(
        regex=r'^teacher_nomini/$',
        view=Teacher_nominiListView.as_view(),
        name='teacher_teacher_nomini_list'
    ),
    url(
        regex=r'^teacher_nomini/archive/(?P<year>\d{4})/'
               '(?P<month>\d{1,2})/$',
        view=Teacher_nominiMonthArchiveView.as_view(),
        name='teacher_teacher_nomini_month_archive'
    ),
    url(
        regex=r'^teacher_nomini/today/$',
        view=Teacher_nominiTodayArchiveView.as_view(),
        name='teacher_teacher_nomini_today_archive'
    ),
    url(
        regex=r'^teacher_nomini/(?P<pk>\d+?)/update/$',
        view=Teacher_nominiUpdateView.as_view(),
        name='teacher_teacher_nomini_update'
    ),
    url(
        regex=r'^teacher_nomini/archive/(?P<year>\d{4})/'
               '(?P<month>\d{1,2})/'
               'week/(?P<week>\d{1,2})/$',
        view=Teacher_nominiWeekArchiveView.as_view(),
        name='teacher_teacher_nomini_week_archive'
    ),
    url(
        regex=r'^teacher_nomini/archive/(?P<year>\d{4})/$',
        view=Teacher_nominiYearArchiveView.as_view(),
        name='teacher_teacher_nomini_year_archive'
    ),
)


from teacher.views.teacher_action_views import *
urlpatterns += patterns('',
    url(
        regex=r'^teacher_action/archive/$',
        view=Teacher_actionArchiveIndexView.as_view(),
        name='teacher_teacher_action_archive_index'
    ),
    url(
        regex=r'^teacher_action/create/$',
        view=Teacher_actionCreateView.as_view(),
        name='teacher_teacher_action_create'
    ),
    url(
        regex=r'^teacher_action/(?P<year>\d{4})/'
               '(?P<month>\d{1,2})/'
               '(?P<day>\d{1,2})/'
               '(?P<pk>\d+?)/$',
        view=Teacher_actionDateDetailView.as_view(),
        name='teacher_teacher_action_date_detail'
    ),
    url(
        regex=r'^teacher_action/archive/(?P<year>\d{4})/'
               '(?P<month>\d{1,2})/'
               '(?P<day>\d{1,2})/$',
        view=Teacher_actionDayArchiveView.as_view(),
        name='teacher_teacher_action_day_archive'
    ),
    url(
        regex=r'^teacher_action/(?P<pk>\d+?)/delete/$',
        view=Teacher_actionDeleteView.as_view(),
        name='teacher_teacher_action_delete'
    ),
    url(
        regex=r'^teacher_action/(?P<pk>\d+?)/$',
        view=Teacher_actionDetailView.as_view(),
        name='teacher_teacher_action_detail'
    ),
    url(
        regex=r'^teacher_action/$',
        view=Teacher_actionListView.as_view(),
        name='teacher_teacher_action_list'
    ),
    url(
        regex=r'^teacher_action/archive/(?P<year>\d{4})/'
               '(?P<month>\d{1,2})/$',
        view=Teacher_actionMonthArchiveView.as_view(),
        name='teacher_teacher_action_month_archive'
    ),
    url(
        regex=r'^teacher_action/today/$',
        view=Teacher_actionTodayArchiveView.as_view(),
        name='teacher_teacher_action_today_archive'
    ),
    url(
        regex=r'^teacher_action/(?P<pk>\d+?)/update/$',
        view=Teacher_actionUpdateView.as_view(),
        name='teacher_teacher_action_update'
    ),
    url(
        regex=r'^teacher_action/archive/(?P<year>\d{4})/'
               '(?P<month>\d{1,2})/'
               'week/(?P<week>\d{1,2})/$',
        view=Teacher_actionWeekArchiveView.as_view(),
        name='teacher_teacher_action_week_archive'
    ),
    url(
        regex=r'^teacher_action/archive/(?P<year>\d{4})/$',
        view=Teacher_actionYearArchiveView.as_view(),
        name='teacher_teacher_action_year_archive'
    ),
)
